---
# This playbook contains common plays that will be run on all nodes.

# set hostname

# in /etc/hostname
- name: Put desired host name in /etc/hostname ( {{ server_host_name }} )
  become: yes
  become_user: root
  template:
    src: etc_hostname.j2
    dest: /etc/hostname

# add to end of 127.0.0.1 line in /etc/hosts
- name: Add host name ( {{ server_host_name }} ) to /etc/hosts.
  become: yes
  become_user: root
  lineinfile:
    dest: /etc/hosts
    backrefs: yes
    regexp: '^(127\.0\.0\.1(?!.*\b{{ server_host_name }}\b).*)'
    line: '\1\t{{ server_host_name }}'

# ==> package installation

# Make sure EPEL is installed.
- name: Ensure EPEL repository is enabled (dnf)
  become: yes
  become_user: root
  dnf: 
    name: epel-release 
    state: present
    update_cache: yes
  notify: dnf-clean-metadata
  when: server_centos_package_manager == "dnf"

- name: Ensure EPEL repository is enabled (yum)
  become: yes
  become_user: root
  yum: 
    name: epel-release 
    state: present
    update_cache: yes
  notify: dnf-clean-metadata
  when: server_centos_package_manager == "yum"

# make sure that important packages are installed
- name: install OpenSSH and dkms (dnf)
  become: yes
  become_user: root
  dnf:
    name:
      - openssh-clients
      - openssh-server
      - dkms
    state: present
  when: server_centos_package_manager == "dnf"

- name: install OpenSSH and dkms (yum)
  become: yes
  become_user: root
  yum:
    name:
      - openssh-clients
      - openssh-server
      - dkms
    state: present
  when: server_centos_package_manager == "yum"

# upgrade - get latest packages
- name: Upgrade installed packages (dnf)
  become: yes
  become_user: root
  dnf:
    name: "*"
    state: latest
  when: server_centos_package_manager == "dnf"

- name: Upgrade installed packages (yum)
  become: yes
  become_user: root
  yum:
    name: "*"
    state: latest
  when: server_centos_package_manager == "yum"

# install development tools.
- name: install the 'Development tools' package group (dnf)
  become: yes
  become_user: root
  dnf:
    name: '@Development tools'
    state: present
  when: server_centos_package_manager == "dnf"

- name: install the 'Development tools' package group (yum)
  become: yes
  become_user: root
  yum:
    name: '@Development tools'
    state: present
  when: server_centos_package_manager == "yum"

# in ~ of ansible user: .vimrc for syntax highlighting, tabs as spaces instead of tabs.
- name: Put .vimrc in place
  template:
    src: template.vimrc.j2
    dest: '/home/{{ ansible_user }}/.vimrc'

# create Downloads folder in ansible_user home if one not already present.
- name: make sure there is a Downloads folder in ansible_user
  file:
    path: ~/Downloads
    state: directory

# create /mnt/cdrom folder.
- name: make sure there is a /media/cdrom folder
  become: yes
  become_user: root
  file:
    path: /media/cdrom
    state: directory