---
# These tasks configure django web applications.

# add django app to apache conf.
- name: add django app to apache conf.
  become: yes
  become_user: root
  template:
    src: django-research.conf.j2
    dest: '/etc/httpd/conf.d/django-{{ django_project_name }}.conf'
  notify: restart httpd
  when:
    - django_configure_apache == true

# --> give apache user access to virtualenv

# add apache user to ansible user group.

# change permissions on ansible user's home folder to 750.

# troubleshooting:
# - https://docs.djangoproject.com/en/3.0/howto/deployment/wsgi/modwsgi/
# - https://stackoverflow.com/questions/55066782/no-module-named-encodings-error-when-deploying-django-app-on-apache-with-mod
# -

# --> static files

# create static folder
- name: make sure there is a static folder
  become: yes
  become_user: root
  file:
    path: "{{ django_static_folder_path }}"
    state: directory
    mode: 0777
  when:
    - django_configure_apache == true

# collect static
- name: run `python manage.py collectstatic` (virtualenv)
  django_manage:
    app_path: "{{ django_project_folder_path }}"
    command: collectstatic --noinput
    virtualenv: "{{ django_virtualenv_path }}"
  when:
    - django_configure_apache == true
    - django_python_env_type == python_env_type_virtualenv

- name: run `python manage.py collectstatic` (conda env)
  shell: source {{ anaconda_base_bin_path }}/activate {{ django_conda_env }} && python manage.py collectstatic --noinput
  args:
    chdir: "{{ django_project_folder_path }}/"
  when:
    - django_configure_apache == true
    - django_python_env_type == python_env_type_conda

# touch wsgi.py to restart wsgi
- name: touch wsgi.py to restart wsgi
  become: yes
  become_user: root
  file:
    path: "{{ django_project_folder_path }}/{{ django_project_name }}/wsgi.py"
    state: touch
  notify:
  - "set-django-project-permissions"
  when:
    - django_configure_apache == true

#- name: Install http and php etc
#  yum: name={{ item }} state=present
#  with_items:
#   - httpd
#   - php
#   - php-mysql
#   - git
#   - libsemanage-python
#   - libselinux-python
#
#- name: insert iptables rule for httpd
#  lineinfile: dest=/etc/sysconfig/iptables create=yes state=present regexp="{{ httpd_port }}" insertafter="^:OUTPUT "
#              line="-A INPUT -p tcp  --dport {{ httpd_port }} -j  ACCEPT"
#  notify: restart iptables
#
#- name: http service state
#  service: name=httpd state=started enabled=yes
#
#- name: Configure SELinux to allow httpd to connect to remote database
#  seboolean: name=httpd_can_network_connect_db state=true persistent=yes
#  when: sestatus.rc != 0

# SELINUX - it is unhappy, just do this... "setsebool -P httpd_enable_homedirs 1"
- name: Configure SELinux to allow httpd to access homedirs
  become: yes
  become_user: root
  shell: "setsebool -P httpd_enable_homedirs 1"
#  seboolean: name=httpd_enable_homedirs state=true persistent=yes
  when:
    - django_configure_apache == true

# and this: setsebool -P httpd_read_user_content 1
- name: Configure SELinux to allow httpd to access user files
  become: yes
  become_user: root
  shell: "setsebool -P httpd_read_user_content 1"
#  seboolean: name=httpd_read_user_content state=true persistent=yes
  when:
    - django_configure_apache == true
