---
# This playbook deploys the apache role.

# Expects new_server and common to already have been run.

#- name: set up new servers
#  hosts: new_servers
#  roles:
#    - new_server

#- name: apply common configuration to all nodes
#  hosts: all
#  roles:
#    - common

- name: configure and deploy Apache HTTP(S) server
  hosts: apache_servers
  roles:
    - apache
