---
# This playbook deploys the whole research application stack.

- name: set up new servers
  hosts: new_servers
  roles:
    - new_server

- name: apply common configuration to all nodes
  hosts: all
  roles:
    - common

- name: configure and deploy Apache HTTP(S) server
  hosts: apache_servers
  roles:
    - apache

- name: set up isolated python environment on server
  hosts: miniconda3_servers
  roles:
    - miniconda3

- name: install and configure mod_wsgi to use miniconda to run Python applications through apache.
  hosts: mod_wsgi_servers
  roles:
    - mod_wsgi

- name: configure and deploy the PostgreSQL database
  hosts: postgres_servers
  roles:
    - postgresql_conda

- name: deploy jupyterhub server
  hosts: jupyterhub_servers
  roles:
    - jupyterhub

#- name: deploy R
#  hosts: r_servers
#  roles:
#    - r

#- name: deploy RStudio server
#  hosts: rstudio_servers
#  roles:
#    - rstudio

- name: deploy django project
  hosts: django_servers
  roles:
    - django_project

