---
# This playbook deploys an apache web server.

- name: set up new servers
  hosts: new_servers
  roles:
    - new_server

- name: apply common configuration to all nodes
  hosts: all
  roles:
    - common

- name: configure and deploy Apache HTTP(S) server
  hosts: apache_servers
  roles:
    - apache

- name: set up isolated python environment on server
  hosts: miniconda3_servers
  roles:
    - miniconda3

- name: install and configure mod_wsgi to use miniconda to run Python applications through apache.
  hosts: mod_wsgi_servers
  roles:
    - mod_wsgi
