---
# This playbook initializes a new server.

- name: set up new servers
  hosts: new_servers
  roles:
    - new_server

- name: apply common configuration to all nodes
  hosts: all
  roles:
    - common
