---
# Handler to handle common notifications. Handlers are called by other plays.
# See http://docs.ansible.com/playbooks_intro.html for more information about handlers.

# Handler showing how to clean dnf metadata cache
- name: dnf-clean-metadata
  become: yes
  become_user: root
  command: dnf clean metadata
  args:
    warn: no

# restart httpd
- name: restart httpd
  become: yes
  become_user: root
  service:
    name: httpd
    state: restarted

# restart apache2
- name: restart apache2
  become: yes
  become_user: root
  service:
    name: httpd
    state: restarted

# reload firewall
- name: reload firewall
  become: yes
  become_user: root
  shell: firewall-cmd --reload

# restart mysqld
- name: restart mysql
  become: yes
  become_user: root
  service:
    name: mysqld
    state: restarted

# django - touch wsgi.py to reload mod_wsgi.
- name: touch wsgi.py
  file:
    path: "{{ django_project_folder_path }}/{{ django_project_name }}/wsgi.py"
    state: touch

# django - if django project folder mode set, recursively set permissions to
#     match.
- name: set-django-project-permissions
  #file:
  #  path: "{{ django_project_folder_path }}"
  #  mode: "{{ django_project_folder_mode }}"
  #  recurse: yes
  shell: find {{ django_project_parent_folder_path }} -type d -exec chmod {{ django_project_folder_mode }} {} \;
  when: ( django_project_folder_mode is defined ) and ( django_project_folder_mode > 0 )
