---
# This playbook will set up the CVNC web application.
# NOTE: uses variables being set in defaults/main.yml to tell when to do steps.
#     Some steps will need to be done first, variables set based on external
#     work, then re-run again.

#------------------------------------------------------------------------------#
# Create a user for the application.
#------------------------------------------------------------------------------#

- name: Create SSH keys for ansible user if not already there.
  user:
    name: "{{ansible_user}}"
    state: "present"
    generate_ssh_key: yes
    ssh_key_bits: 4096
    ssh_key_file: .ssh/id_rsa

# EXTERNAL: add public key to authorized_keys on server, then:
# - ssh into server from command line as user cvnc once, to verify SSH stuff: ssh 205.145.140.65
# - in defaults/main.yml, set "do_git: true".

# set up directories

- name: make {{ project_name }} home
  file:
    path: "{{ project_home_folder_path }}"
    state: directory

- name: make sure there is a django folder in {{ project_name }} home
  file:
    path: "{{ project_django_folder_path }}"
    state: directory

- name: make sure there is a django/logs folder in {{ project_name }} home
  file:
    path: "{{ project_django_logs_folder_path }}"
    state: directory

- name: make sure there is a django/logs/{{ project_name }}-dev.log file, permissions 777.
  file:
    path: "{{ project_django_logs_folder_path }}/{{ project_name }}-dev.log"
    state: touch
    mode: '1777'

- name: make sure there is a backups folder in {{ project_name }} home
  file:
    path: "{{ project_backup_folder_path }}"
    state: directory

#------------------------------------------------------------------------------#
# cvnc git repo cloning
#------------------------------------------------------------------------------#

- name: git repo cloning
  include: git.yml
  when: do_git == true

#------------------------------------------------------------------------------#
# cvnc mysql setup
#------------------------------------------------------------------------------#

# MANUAL
# - download database backup to ~/backups and gunzip.
# - update defaults/main.yml:
#     - db_dump_file_name
#     - do_db: true

- name: database setup include
  include: database.yml
  when: do_db == true

#------------------------------------------------------------------------------#
# python
#------------------------------------------------------------------------------#

- name: python setup include
  include: python.yml
  when: do_python == true

# virtual host for apache
