# related variables
ansible_user_home_folder: "/home/{{ ansible_user }}"
anaconda_base_path: "/opt/miniconda3"
anaconda_base_bin_path: "{{ anaconda_base_path }}/bin"
anaconda_base_python: "{{ anaconda_base_bin_path }}/python3"
virtualenv_parent_folder: "{{ ansible_user_home_folder }}"
virtualenv_folder: "{{ virtualenv_parent_folder }}/.virtualenvs"
work_folder: "{{ ansible_user_home_folder }}/work"
log_folder: "{{ ansible_user_home_folder }}/logs"
server_webroot_folder: /var/www/html

# project basics
django_project_name: research
django_database_type: "mysql"  # for now, supported: "mysql", "postgresql"

# django project virtualenv
django_virtualenv_from_env: "{{ anaconda_base_path }}"
django_virtualenv_from_env_bin: "{{ anaconda_base_bin_path }}"
django_virtualenv_from_env_python: "{{ anaconda_base_python }}"  # python where virtualenv and virtualenvwrapper are installed, used to create virtualenv.
django_virtualenv_name: "{{ django_project_name }}"
django_virtualenv_path: "{{ virtualenv_folder }}/{{ django_virtualenv_name }}"
django_virtualenv_bin_path: "{{ django_virtualenv_path }}/bin"

# django project database configuration
db_postgresql_python_package: "psycopg2"
db_postgresql_port: "5432"
db_mysql_python_package: "mysqlclient"
db_mysql_port: "3306"
django_db_python_package: "{{ db_mysql_python_package }}"
django_db_package: "{{ django_db_python_package }}"  # "pyscopg2" for postgresql; "mysqlclient" for MySQL
django_db_name: "{{ django_project_name }}"
django_db_username: "django_user"
django_db_password: "{{ ansible_become_password }}"
django_db_host: "localhost"
django_db_port: "{{ db_postgresql_port }}"  # 5432 for postgresql, 3306 for mysql.

# django project locations configuration
django_project_parent_folder_path: "{{ work_folder }}/django"
django_project_folder_path: "{{ django_project_parent_folder_path }}/{{ django_project_name }}"
django_config_folder_path: "{{ django_project_folder_path }}/{{ django_project_name }}"
django_log_file_path: "{{ log_folder }}/django-{{ django_project_name }}.log"
django_static_folder_path: "{{ server_webroot_folder }}/static"
django_settings_import: "{{ django_project_name }}.settings"

# django user setup.
django_superuser_username: "{{ ansible_user }}"
django_superuser_password: "{{ ansible_become_password }}"
django_superuser_email: ""
