# project_name
project_name: cvnc
project_host_username: cvnc
project_host_url: 205.145.140.65

# git repos
do_git: false
git_user: 

# database
do_db: false
db_name: cvnc
db_user_name: cvnc
db_password: today123
db_dump_file_name: cvnc_2020-06-19_02h00m.Friday.sql