---
# Handler to handle DB tier notifications

- name: restart postgresql
  shell: source {{ anaconda_bin_path }}/activate {{ postgresql_conda_env }} && pg_ctl -D {{ postgresql_data_path }} -l {{ postgresql_home_path }}/logfile-{{ ansible_date_time.iso8601_basic_short }} restart

# reload firewall
- name: reload firewall
  become: yes
  become_user: root
  shell: firewall-cmd --reload
