---
# Handler to handle DB tier notifications

- name: restart postgresql
  shell: source {{ anaconda_bin_path }}/activate {{ postgresql_conda_env }} && pg_ctl -D {{ postgresql_data_path }} -l {{ postgresql_log_path }}/logfile-$( date "+%Y%m%dT%H%M%S" ) restart

# reload firewall
- name: reload firewall
  become: yes
  become_user: root
  shell: firewall-cmd --reload
