---
#==============================================================================#
# Install mod_wsgi using pip.
#==============================================================================#

# note: assuming that base python is anaconda.

#------------------------------------------------------------------------------#
# compile and install mod_wsgi

# install mod_wsgi package in base python environment using pip.
- name: install mod_wsgi in base anaconda python environment ( {{ python_home_path }} ) using pip in {{ python_bin_folder_path }}.
  become_user: root
  become_method: sudo
  shell: source {{ python_bin_folder_path }}/activate && {{ python_bin_folder_path }}/pip install mod_wsgi
  when:
    - mod_wsgi_install_type == mod_wsgi_install_type_pip

# stop apache
- name: stop httpd
  become: yes
  become_user: root
  service:
    name: httpd
    state: stopped

# copy resulting ".so" file to {{ mod_wsgi_so_path }}
- name: Copy {{ mod_wsgi_pip_so_file_path }} to {{ mod_wsgi_so_path }}.
  become: yes
  become_user: root
  copy:
    src: "{{ mod_wsgi_pip_so_file_path }}"
    dest: "{{ mod_wsgi_so_path }}"
    remote_src: yes

#------------------------------------------------------------------------------#
# add mod_wsgi to apache

# place mod_wsgi conf in {{ wsgi_conf_file_path }}
- name: place mod_wsgi conf in {{ wsgi_conf_file_path }}
  become: yes
  become_user: root
  template:
    src: wsgi.conf.j2
    dest: "{{ wsgi_conf_file_path }}"
  notify: restart httpd

# More details on needing WSGIPythonHome: https://groups.google.com/forum/#!topic/modwsgi/1oEuIHDiCbM

#------------------------------------------------------------------------------#
# start apache

# start apache
- name: start httpd
  become: yes
  become_user: root
  service:
    name: httpd
    state: started
