---
# This playbook will compile and install mod_wsgi, compiled to work with the
#     Python install specified in the variable {{ mod_wsgi_python_bin_path }}.
# NOTE: uses variables being set in defaults/main.yml.

#------------------------------------------------------------------------------#
# Apache 2.4 mod_wsgi
#------------------------------------------------------------------------------#

#------------------------------------------------------------------------------#
# first, archive old install
- name: clean up old install of mod_wsgi
  import_tasks: clean.yml

#==============================================================================#
# ==> install mod_wsgi...

- name: Install mod_wsgi from source.
  import_tasks: install_from_source.yml
  when:
    - mod_wsgi_install_type == mod_wsgi_install_type_source

- name: Install mod_wsgi using pip.
  import_tasks: install_with_pip.yml
  when:
    - mod_wsgi_install_type == mod_wsgi_install_type_pip

# BROKEN - do not install with conda.
#- name: Install mod_wsgi using conda.
#  import_tasks: install_with_conda.yml
#  when:
#    - mod_wsgi_install_type == mod_wsgi_install_type_conda
