#===============================================================================
# ==> what action?

- name: Remove existing mod_wsgi
  include: clean.yml
  when: mod_wsgi_action == "clean"

- name: Install mod_wsgi (including clean)
  include: install.yml
  when: mod_wsgi_action == "install"

