#===============================================================================
# ==> what action?

- name: Remove existing mod_wsgi
  import_tasks: clean.yml
  when: mod_wsgi_action == "clean"

- name: Install mod_wsgi (including clean)
  import_tasks: install.yml
  when: mod_wsgi_action == "install"
