# python
python_2_pip_executable: "/usr/bin/pip2"
python_3_pip_executable: "/usr/local/bin/pip3"
anaconda_pip_executable: "/opt/miniconda3/bin/pip3"
jupyterhub_pip_executable: "{{ anaconda_pip_executable }}"
jupyterhub_configproxy_auth_token: replaceme
jupyterhub_config_folder: /etc/jupyterhub
jupyterhub_proxy_command_path: ""
jupyterhub_admin_user_list: "'{{ ansible_user }}'"
jupyterhub_whitelist_list:
jupyterhub_ssl_certificate_path: "{{ server_ssl_certificate_path }}"
jupyterhub_ssl_private_key_path: "{{ server_ssl_private_key_path }}"
