---
# Handler to handle DB tier notifications

- name: restart postgresql-{{ server_pgsql_version }}
  become: yes
  become_user: root
  service:
    name: postgresql-{{ server_pgsql_version }}
    state: restarted

# reload firewall
- name: reload firewall
  become: yes
  become_user: root
  shell: firewall-cmd --reload
