# postgresql via conda
server_pgsql_version: 12
anaconda_install_folder: /opt/miniconda3
anaconda_bin_path: "{{ anaconda_install_folder }}/bin"
anaconda_base_bin_path: "{{ anaconda_bin_path }}"
postgresql_user: "{{ ansible_user }}"
postgresql_conda_env: "postgresql_service"
postgresql_home_path: "{{ ansible_user_home_folder }}/postgresql"
postgresql_data_folder_name: postgresql_data
postgresql_data_path: "{{ postgresql_home_path }}/{{ postgresql_data_folder_name }}"
postgresql_log_path: "{{ postgresql_home_path }}/logs"
postgresql_config_path: "{{ postgresql_data_path }}"
postgresql_command_prefix: "source {{ anaconda_bin_path }}/activate {{ postgresql_conda_env }} && "
